
name: sistema_promissorias
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  postgres: ^3.0.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sprintf: ^7.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
